### PR TITLE
upd: Sorting all translate files & Turkish strings translated.

### PR DESCRIPTION
**Pull request by ramazansancar**
upd: Sorting all translate files
upd: Turkish language translation has been updated.

I refactored the Translate Tool to make it suitable for this project and edited it.

Translate Tool: https://github.com/ramazansancar/AndroidStringXmlTranslator

Translate Tool Source: https://jtbrinkmann.de/tools/android-strings.xml-translator.html (Source: https://github.com/yuliskov/SmartTube > "[Translate the app](https://jtbrinkmann.de/tools/android-strings.xml-translator.html)") Contrubitor: @yuliskov

### CODE REVIEW

**Comment by emanuele-f** [comment]
Hello, PCAPdroid relies on weblate for translations. Your changes would probably create conflicts with it and be overwritten by the changes performed on weblate

**Comment by emanuele-f** [comment]
I see, thanks for reporting this, I will check

**Comment by ramazansancar** [comment]
> I see, thanks for reporting this, I will check

Do we include this PR? @emanuele-f

**Comment by emanuele-f** [comment]
@ramazansancar we cannot merge this, otherwise it will conflict with weblate.

On weblate I can see the "The VCS repository is not up to date" alert, but that does not prevent me from creating new strings. Can you send a screenshot of the warning/error which does not allow you to make modifications there?

**Comment by ramazansancar** [comment]
> @ramazansancar we cannot merge this, otherwise it will conflict with weblate.
> 
> On weblate I can see the "The VCS repository is not up to date" alert, but that does not prevent me from creating new strings. Can you send a screenshot of the warning/error which does not allow you to make modifications there?

All translate: "This string is read-only"

image

**Comment by emanuele-f** [comment]
That string was set readonly by me, because it's the app name and should not be translated. Clicking on the "not translated" filter allows you to see only the strings that need to be translated

**Comment by ramazansancar** [comment]
> That string was set readonly by me, because it's the app name and should not be translated. Clicking on the "not translated" filter allows you to see only the strings that need to be translated

This is the case for all strings. @emanuele-f

**Comment by emanuele-f** [comment]
@ramazansancar sorry for the late reply. I will check this issue in more detail just before the 1.7.0 release. In any case, your strings will be integrated, either via this PR or via weblate (possibly via its "import" feature)

**Comment by ramazansancar** [comment]
> @ramazansancar sorry for the late reply. I will check this issue in more detail just before the 1.7.0 release. In any case, your strings will be integrated, either via this PR or via weblate (possibly via its "import" feature)

Thanks

**Comment by emanuele-f** [comment]
I've fixed the issues on the weblate platform and updated the translations. Only 21 strings remain to be translated on weblate, so please update the translation there. If you have any issue please post a new screenshot here.

**Comment by emanuele-f** [comment]
Another user has already updated the Turkish translation, so I'm closing this.

**Pull request closed without merging**
