### PR TITLE
Weblate mentioned in README

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by emanuele-f** [comment]
Postponing this as well as public announcement after weblate project approval. Thanks for your translation contribution.

**Comment by comradekingu** [comment]
@emanuele-f As people will start translating early since it is in https://hosted.weblate.org/changes/?action=51&action=50 https://github.com/emanuele-f/PCAPdroid/pull/174/files might help avoid duplicated effort.

**Comment by emanuele-f** [comment]
The weblate project is [currently locked](https://hosted.weblate.org/projects/pcapdroid/app/) due to some problems with merge conflicts (see https://github.com/WeblateOrg/weblate/issues/7081). This will prevent users from translating strings for now. I'm currently looking for the correct recipe for the localization, maybe you can provide some pointers in this context.

These are the requirements I'm looking for:
- People should not be forced to use weblate for translation. Contribution with pull requests should be supported.
- I don't want partially localized languages (e.g. new languages work-in-progress) to go into production. E.g I only accept a language PR if all the strings are localized.
- I don't want the commits history of the repo to be polluted with localization commits. Commits should only occur when a language is fully localized.
- I'm against continuous localization if it means that commits are automatically pushed to the repo. I want to choose what to push to prevent partially-localized languages or poor quality.
- I don't want translators to waste their time with work-in-progress strings. This is why I work on the `dev` branch for new features and I only merge to `master` when strings are stable enough.

**Comment by comradekingu** [comment]
Could use a "translation" branch, and rebase on that come time to put out a release?
I would not keep language work away from translators, nor keep translator work away from users.
The easier it is to do something about it, the less one has to worry about the perfect solution not being imperfect.

I wonder what Weblate does when someone is added as a co-author of a commit.

**Comment by emanuele-f** [comment]
> Could use a "translation" branch, and rebase on that come time to put out a release?

A translation branch is an option, but it complicates things. Since the conflict is now solved, I think I'll go with manual squash/merge from weblate for now.

> I would not keep language work away from translators, nor keep translator work away from users.

It makes sense to allow people to see the effects of their translation in place. I will think about this. A github workflow already allows them to download an apk from the latest commits without the need to wait for an official release or manual build.

> I wonder what Weblate does when someone is added as a co-author of a commit.

This is something I've also seen when dealing with PR on github. I think if I cherry-pick and squash the commits from the weblate branch it will have this effect.

**Pull request merged**
