### PR TITLE
Add stats for IPv6 traffic

### PR DESCRIPTION
**Pull request by myzhan**
I need to know the IPv6 traffic percentage. For convenience, I add it to the CaptureStatus textview. Not sure it's appropriate or not. Please let me know if there is a better place. And translations are needed.

image

image

### CODE REVIEW

**Comment by emanuele-f** [comment]
Hi @myzhan, thanks for this contibution.
I would only add the stats to the Stats activity, not to the StatusFragment. Is this enough for your needs?

**Comment by myzhan** [comment]
> Hi @myzhan, thanks for this contibution. I would only add the stats to the Stats activity, not to the StatusFragment. Is this enough for your needs?

OK, I will move the percentage to the Stats activity later.

**Comment by myzhan** [comment]
OK, I have moved it to the StatsActivity.

image

**Comment by emanuele-f** [comment]
@myzhan I've done some small changes.
Last question, do you really need decimals in the IPv6 traffic percentage (e.g. 65.77%) or without decimals (e.g. 66%, or 66.8%) it's ok for you? By removing the decimals, it can be consistent with the heap and memory usages percentages.

**Comment by myzhan** [comment]
Both 66% and 66.8% are ok.

Emanuele Faranda ***@***.***>于2024年3月12日 周二00:38写道：

**Pull request merged**
